name: sigal_python3p6_pytorch1p5
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - joblib=1.0.1=pyhd3eb1b0_0
  - pandas=1.1.5=py36ha9443f7_0
  - pytz=2021.3=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py36ha9443f7_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - cairo=1.16.0=h6cf1ce9_1008
  - colorama=0.4.5=pyhd8ed1ab_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h48d8840_2
  - expat=2.4.8=h27087fc_0
  - ffmpeg=4.3.2=h37c90e5_3
  - fontconfig=2.14.0=h8e229c2_0
  - gettext=0.19.8.1=h0b5b191_1005
  - glib=2.68.4=h9c3ff4c_0
  - glib-tools=2.68.4=h9c3ff4c_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.18.4=h29181c9_0
  - gstreamer=1.18.5=h76c114f_0
  - harfbuzz=2.9.1=h83ec7ef_1
  - hdf5=1.12.1=nompi_h2386368_104
  - icu=68.2=h9c3ff4c_0
  - jasper=1.900.1=h07fcdf6_1006
  - jbig=2.1=h7f98852_2003
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.3.1=py36h605e78d_1
  - krb5=1.19.3=h3790be6_0
  - lame=3.100=h7f98852_1001
  - lerc=3.0=h9c3ff4c_0
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=5_h92ddd45_netlib
  - libclang=11.1.0=default_ha53f305_1
  - libcurl=7.83.1=h7bff187_0
  - libdeflate=1.10=h7f98852_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.10=h9b69904_4
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.68.4=h3e27bee_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=5_h92ddd45_netlib
  - liblapacke=3.9.0=5_h92ddd45_netlib
  - libllvm11=11.1.0=hf817b99_3
  - libnghttp2=1.47.0=h727a467_0
  - libopencv=4.5.3=py36h9976982_2
  - libpq=13.5=hd57d9b9_1
  - libprotobuf=3.16.0=h780b84a_0
  - libssh2=1.10.0=ha56f1ee_2
  - libtiff=4.3.0=h542a066_3
  - libuuid=2.32.1=h7f98852_1000
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.12=h72842e0_0
  - libzlib=1.2.12=h166bdaf_2
  - matplotlib=3.3.4=py36h5fab9bb_0
  - matplotlib-base=3.3.4=py36hd391965_0
  - mysql-common=8.0.29=haf5c9bc_1
  - mysql-libs=8.0.29=h28c427c_1
  - nettle=3.6=he412f7d_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.77=h2350873_0
  - opencv=4.5.3=py36h5fab9bb_2
  - openh264=2.1.1=h780b84a_0
  - pcre=8.45=h9c3ff4c_0
  - pixman=0.40.0=h36c2ea0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - py-opencv=4.5.3=py36he75451f_2
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py36h5fab9bb_7
  - pyqt-impl=5.12.3=py36h7ec31b9_7
  - pyqt5-sip=4.19.18=py36hc4f0c31_7
  - pyqtchart=5.12=py36h7ec31b9_7
  - pyqtwebengine=5.12.1=py36h7ec31b9_7
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - qt=5.12.9=hda022c4_4
  - scipy=1.5.3=py36h81d768a_1
  - tornado=6.1=py36h8f6f2f9_1
  - tqdm=4.64.0=pyhd8ed1ab_0
  - x264=1!161.3030=h7f98852_1
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.0.10=h7f98852_0
  - xorg-libsm=1.2.3=hd9c2040_1000
  - xorg-libx11=1.7.2=h7f98852_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h7f98852_1
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - blas=1.0=mkl
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2020.2=254
  - jpeg=9e=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.3=h5eee18b_3
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1q=h7f8727e_0
  - pillow=8.3.1=py36h5aabda8_0
  - pip=10.0.1=py36_0
  - python=3.6.10=h7579374_2
  - readline=8.1.2=h7f8727e_1
  - setuptools=58.0.4=py36h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pytorch=1.5.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - torchvision=0.6.0=py36_cu102
  - pip:
    - attrs==21.4.0
    - charset-normalizer==2.0.12
    - clearml==1.6.2
    - furl==2.1.3
    - future==0.18.2
    - idna==3.3
    - importlib-metadata==4.8.3
    - jsonschema==4.0.0
    - orderedmultidict==1.0.1
    - pathlib2==2.3.7.post1
    - psutil==5.9.1
    - pyjwt==2.4.0
    - pyqt5==5.12.3
    - pyrsistent==0.18.0
    - pyyaml==6.0
    - requests==2.27.1
    - torch==1.5.0
    - typing-extensions==4.1.1
    - urllib3==1.26.10
    - zipp==3.6.0
prefix: /home/sigalr/.conda/envs/sigal_python3p6_pytorch1p5

